// Il percorso: cosa studiare, in quale ordine, e come sapere di averlo fatto.
//
// Criterio dell'ordine: ogni passo aggiunge UNA difficoltà sola. Un accordo nuovo non
// arriva insieme a un ritmo nuovo, e un ritmo nuovo si prova su un accordo che le dita
// già conoscono. È il motivo per cui il Fa arriva prima del Sol pur essendo "dopo"
// nell'alfabeto: costa due dita invece di tre.
//
// L'ordine non è un'opinione: `collaudo.html` verifica che nessun passo chieda un accordo
// non ancora introdotto. Le eccezioni esistono ma vanno DICHIARATE in `dati.tollera`,
// così una scorciatoia didattica resta una scelta e non diventa una svista.
//
// Tipi di passo:
//   accordatura — apre l'accordatore, si chiude da sé quando le quattro corde sono a posto
//   lettura     — una scheda da leggere, con domanda di controllo
//   accordo     — la forma nuova: la premi, la suoni, la togli, la rimetti
//   ascolta     — il microfono verifica che l'accordo suoni davvero come deve
//   orecchio    — allenamento dell'orecchio: riconoscere senza guardare
//   cambio      — l'esercizio che fa la differenza: due accordi a tempo di metronomo
//   ritmo       — mano destra sul telaio del ritmo (pennata o arpeggio)
//   giro        — suonare un giro o un brano dall'inizio alla fine

const P = (id, tipo, titolo, testo, obiettivo, dati = {}) =>
  ({ id, tipo, titolo, testo, obiettivo, dati });

export const LIVELLI = [
  {
    id: 'l0',
    nome: 'Livello 0 — Prima di suonare',
    sottotitolo: 'Strumento accordato, mano destra, come si legge un diagramma',
    passi: [
      P('l0-accorda', 'accordatura',
        'Accorda le quattro corde',
        'Uno strumento scordato insegna l\'intonazione sbagliata: l\'orecchio impara quello che sente. Prima di ogni sessione, trenta secondi qui.',
        'Tutte e quattro le corde entro 5 centesimi',
        {}),
      P('l0-mano', 'lettura',
        'Come si tiene e come si penna',
        '',
        'Risposta esatta alla domanda',
        {
          punti: [
            'L\'ukulele si appoggia sull\'avambraccio destro, la cassa contro il petto: non lo tieni con la mano sinistra, che deve restare libera di muoversi.',
            'La mano sinistra: pollice dietro il manico a metà altezza, dita curve, si preme con la PUNTA del dito subito dietro la barretta del tasto, non sopra.',
            'La mano destra penna dove il manico incontra la cassa, non in mezzo alle corde: lì il suono è più definito.',
            'La pennata in giù si fa col dorso dell\'unghia dell\'indice, quella in su col polpastrello dello stesso dito. Il movimento parte dal polso, non dal gomito.',
            'Se una corda ronza, il dito è troppo lontano dal tasto o preme di lato. Non è forza che manca: è posizione.',
          ],
          quiz: [{
            d: 'Dove va la punta del dito quando premi un tasto?',
            opzioni: ['Sopra la barretta di metallo', 'Subito dietro la barretta, verso la cassa', 'A metà fra due barrette'],
            giusta: 1,
            perche: 'Premendo subito dietro la barretta la corda si ferma esattamente lì e serve poca forza. A metà tasto la nota esce sorda e devi schiacciare il triplo.',
          }],
        }),
      P('l0-diagramma', 'lettura',
        'Leggere un diagramma di accordo',
        '',
        'Risposta esatta alla domanda',
        {
          punti: [
            'Il manico è disegnato in verticale, come se guardassi lo strumento con la paletta in alto.',
            'Le quattro linee verticali sono le corde: da sinistra a destra G, C, E, A. Sull\'ukulele standard la G è la più acuta delle prime due — non è un errore.',
            'La linea spessa in alto è il capotasto. Le linee orizzontali sotto sono i tasti.',
            'Un pallino dice dove premere; il numero dentro è il dito (1 indice, 2 medio, 3 anulare, 4 mignolo).',
            'Un cerchio vuoto sopra il capotasto = corda suonata libera. Una ✕ = corda da non far suonare.',
            'Una capsula lunga = un dito solo che preme più corde insieme: si chiama barré.',
            'Se in alto a sinistra c\'è scritto "5fr", il diagramma non parte dal capotasto ma dal 5° tasto.',
          ],
          quiz: [{
            d: 'In un diagramma, la corda più a sinistra qual è?',
            opzioni: ['La A, la più acuta', 'La G', 'La C, la più grave'],
            giusta: 1,
            perche: 'L\'ordine è sempre G C E A da sinistra a destra: è l\'ordine in cui le vedi tenendo lo strumento in posizione di suono.',
          }],
        }),
      P('l0-pennata', 'ritmo',
        'Quattro pennate a vuoto',
        'Senza premere niente: solo la mano destra e il metronomo. Serve a far combaciare il tuo tempo con un tempo esterno, che è la cosa più difficile di tutte e non c\'entra con le dita.',
        '16 battute a 70 bpm senza perdere il tempo',
        { ritmo: 'r-giu4', accordo: null, bpm: 70, battute: 16 }),
    ],
  },

  {
    id: 'l1',
    nome: 'Livello 1 — Due accordi e una canzone',
    sottotitolo: 'Do e La minore: un dito ciascuno, e sei già in grado di accompagnare',
    passi: [
      P('l1-do', 'accordo',
        'Do maggiore',
        'Un dito solo. Punta l\'anulare sul terzo tasto della corda A (la più a destra) e penna tutte e quattro le corde. Se qualcosa ronza, avvicina il dito alla barretta.',
        'Suonarlo pulito 8 volte di fila',
        { accordo: 'C', ripetizioni: 8 }),
      P('l1-lam', 'accordo',
        'La minore',
        'Ancora un dito: il medio sul secondo tasto della corda G, quella più a sinistra. È il fratello triste del Do: le stesse tre note, una spostata.',
        'Suonarlo pulito 8 volte di fila',
        { accordo: 'Am', ripetizioni: 8 }),
      P('l1-cambio', 'cambio',
        'Cambio Do ↔ La minore',
        'Qui si impara davvero. Il segreto non è la velocità delle dita ma ANTICIPARE: la mano sinistra deve partire mentre la destra suona l\'ultima pennata della battuta, non dopo.',
        '16 battute a 60 bpm',
        { accordi: ['C', 'Am'], bpm: 60, battute: 16 }),
      P('l1-ritmo', 'ritmo',
        'Otto pennate su un accordo',
        'Giù-su continuo, senza fermarsi mai. Tieni il Do premuto e pensa solo al polso.',
        '16 battute a 70 bpm',
        { ritmo: 'r-otto', accordo: 'C', bpm: 70, battute: 16 }),
      P('l1-giro', 'giro',
        'Il tuo primo giro',
        'Due battute di Do, due di La minore. Un accordo ogni quattro pennate.',
        'Il giro intero senza fermarti',
        { brano: 'giro-c-am', bpm: 64 }),
      P('l1-fra', 'giro',
        'Fra Martino campanaro',
        'La prima canzone vera. Nell\'ultima riga c\'è un Sol settima che non hai ancora imparato: per oggi suona Do anche lì — funziona lo stesso e sentirai da te che manca qualcosa. Lo impari nel livello 2.',
        'Suonarla dall\'inizio alla fine',
        { brano: 'fra-martino', bpm: 84, tollera: ['G7'] }),
    ],
  },

  {
    id: 'l2',
    nome: 'Livello 2 — Fa, Sol settima, e il ritmo classico',
    sottotitolo: 'Due e tre dita, il pattern di pennata che sentirai in ogni video, e il microfono che ti dice se è pulito',
    passi: [
      P('l2-fa', 'accordo',
        'Fa maggiore',
        'Il primo accordo a due dita: indice sul 1° tasto della E, medio sul 2° della G. Le due dita non sono affiancate ma in diagonale, e le corde C e A restano libere.',
        'Suonarlo pulito 8 volte di fila',
        { accordo: 'F', ripetizioni: 8 }),
      P('l2-ascolta-fa', 'ascolta',
        'Il microfono controlla il tuo Fa',
        'Da qui in poi non sei più solo tu a giudicare. Il programma ascolta le note che escono davvero e ti dice se ci sono tutte: sul Fa l\'errore tipico è che l\'indice tocchi la corda A e la spenga, e a orecchio nudo non te ne accorgi.',
        '4 accordi riconosciuti come corretti',
        { accordo: 'F', corretti: 4 }),
      P('l2-cambio-cf', 'cambio',
        'Cambio Do ↔ Fa',
        'Nessun dito in comune: la mano deve aprirsi e chiudersi. Fai il movimento a vuoto, senza suonare, dieci volte, poi metti il metronomo.',
        '16 battute a 60 bpm',
        { accordi: ['C', 'F'], bpm: 60, battute: 16 }),
      P('l2-cambio-amf', 'cambio',
        'Cambio La minore ↔ Fa',
        'Qui c\'è un regalo: il medio sulla G al 2° tasto NON si muove. Tienilo giù e aggiungi solo l\'indice.',
        '16 battute a 66 bpm',
        { accordi: ['Am', 'F'], bpm: 66, battute: 16 }),
      P('l2-ritmo', 'ritmo',
        'Il ritmo classico: D DU UDU',
        'Il ritmo più usato sull\'ukulele. Regola unica: la mano non si ferma mai. Nei buchi passa comunque, senza toccare le corde. Se la fermi, il tempo si perde.',
        '16 battute a 66 bpm',
        { ritmo: 'r-classico', accordo: 'C', bpm: 66, battute: 16 }),
      P('l2-giro', 'giro',
        'Giro Do · Fa',
        'Il salto più comune della musica occidentale, da fare a memoria.',
        'Il giro intero senza fermarti',
        { brano: 'giro-c-f', bpm: 70 }),
      P('l2-sol7', 'accordo',
        'Sol settima',
        'Prima il Sol settima che il Sol maggiore: costa le stesse tre dita ma la forma è più comoda, e serve più spesso perché chiude le frasi.',
        'Suonarlo pulito 8 volte di fila',
        { accordo: 'G7', ripetizioni: 8 }),
      P('l2-cambio-cg7', 'cambio',
        'Cambio Do ↔ Sol settima',
        'Il cambio che chiude qualunque canzone. Il Sol settima "tira" verso il Do: lo sentirai.',
        '16 battute a 66 bpm',
        { accordi: ['C', 'G7'], bpm: 66, battute: 16 }),
      P('l2-orecchio', 'orecchio',
        'Allegro o triste? maggiore contro minore',
        'Nessun diagramma: senti l\'accordo e dici se è maggiore o minore. È la distinzione più importante che esista e si impara in mezz\'ora, ma solo se la si esercita separatamente dalle dita.',
        '6 risposte esatte',
        { modo: 'maggiore-minore', opzioni: ['C', 'Am', 'F', 'Dm', 'G'], corrette: 6, tollera: ['Dm', 'G'] }),
      P('l2-fattoria', 'giro',
        'Nella vecchia fattoria',
        'Tre accordi: Do, Fa e Sol settima. Il Fa entra ed esce in fretta.',
        'Suonarla dall\'inizio alla fine',
        { brano: 'vecchia-fattoria', bpm: 88 }),
      P('l2-susanna', 'giro',
        'Oh Susanna',
        'Do e Sol settima a ritmo allegro. Provala col ritmo classico appena imparato.',
        'Suonarla dall\'inizio alla fine',
        { brano: 'oh-susanna', bpm: 92 }),
      P('l2-jingle', 'giro',
        'Jingle Bells',
        'Tre accordi e un ritornello che sanno tutti: è il primo pezzo da suonare davanti a qualcuno.',
        'Suonarla dall\'inizio alla fine',
        { brano: 'jingle-bells', bpm: 96 }),
    ],
  },

  {
    id: 'l3',
    nome: 'Livello 3 — Sol maggiore e il giro dei quattro accordi',
    sottotitolo: 'Tre dita insieme e la struttura che regge mezza classifica',
    passi: [
      P('l3-sol', 'accordo',
        'Sol maggiore',
        'Tre dita in triangolo: indice C-2, medio A-2, anulare E-3. Il polso va basso, altrimenti l\'anulare non arriva. Le prime volte fa male: è normale, non è forza che manca.',
        'Suonarlo pulito 8 volte di fila',
        { accordo: 'G', ripetizioni: 8 }),
      P('l3-ascolta-sol', 'ascolta',
        'Il microfono controlla il tuo Sol',
        'Con tre dita in fila la corda A viene spenta quasi sempre dal palmo. Suonalo e guarda quali note arrivano davvero.',
        '4 accordi riconosciuti come corretti',
        { accordo: 'G', corretti: 4 }),
      P('l3-cambio-fg', 'cambio',
        'Cambio Fa ↔ Sol',
        'Da due dita a tre, e nessuna in comune. Il cambio più scomodo dei primi mesi: fallo lento e pulito, non veloce e sporco.',
        '16 battute a 56 bpm',
        { accordi: ['F', 'G'], bpm: 56, battute: 16 }),
      P('l3-cambio-gam', 'cambio',
        'Cambio Sol ↔ La minore',
        'Tre dita che si sciolgono in una. Il difficile è il ritorno.',
        '16 battute a 60 bpm',
        { accordi: ['G', 'Am'], bpm: 60, battute: 16 }),
      P('l3-numeri', 'lettura',
        'Perché quattro accordi bastano',
        '',
        'Risposta esatta alla domanda',
        {
          punti: [
            'In una tonalità gli accordi si numerano con i numeri romani. In Do maggiore: I = Do, ii = Re minore, iii = Mi minore, IV = Fa, V = Sol, vi = La minore.',
            'Maiuscolo = maggiore, minuscolo = minore. Il V diventa spesso V7 (Sol settima) perché aumenta la voglia di tornare al I.',
            'Il giro I–V–vi–IV (Do · Sol · La minore · Fa) è la struttura di centinaia di canzoni pop degli ultimi cinquant\'anni.',
            'Cambiare tonalità significa traslare gli stessi numeri: in Sol maggiore, I–V–vi–IV diventa Sol · Re · Mi minore · Do.',
            'Ecco perché non serve imparare mille accordi: servono i quattro giusti della tonalità in cui stai suonando.',
          ],
          quiz: [{
            d: 'In Do maggiore, qual è il grado V?',
            opzioni: ['Fa', 'Sol', 'La minore'],
            giusta: 1,
            perche: 'Il V è il quinto grado della scala: Do(I) Re(ii) Mi(iii) Fa(IV) Sol(V). Il Fa è il IV, il La minore il vi.',
          }],
        }),
      P('l3-giro4', 'giro',
        'Il giro dei quattro accordi',
        'Do · Sol · La minore · Fa. Quando lo suoni sciolto, sai accompagnare una quantità imbarazzante di canzoni.',
        'Il giro intero senza fermarti',
        { brano: 'giro-quattro', bpm: 68 }),
      P('l3-ritmo', 'ritmo',
        'Ritmo da ballata',
        'Fermo sui primi due battiti, si apre sugli ultimi due. Provalo sul giro dei quattro accordi.',
        '16 battute a 70 bpm',
        { ritmo: 'r-ballata', accordo: 'G', bpm: 70, battute: 16 }),
      P('l3-cambio-veloce', 'cambio',
        'I quattro accordi a sorteggio',
        'Do, Sol, La minore e Fa mescolati: senza l\'ordine prevedibile del giro, le dita devono sapere dove andare invece di ricordare la sequenza.',
        '20 battute a 66 bpm',
        { accordi: ['C', 'G', 'Am', 'F'], bpm: 66, battute: 20, sorteggio: true }),
    ],
  },

  {
    id: 'l4',
    nome: 'Livello 4 — Minori, settime, groove',
    sottotitolo: 'Il colore: la stessa canzone cambia faccia',
    passi: [
      P('l4-rem', 'accordo',
        'Re minore',
        'Tre dita in un grappolo strettissimo: indice E-1, medio C-2, anulare G-2. La corda A resta libera.',
        'Suonarlo pulito 8 volte di fila',
        { accordo: 'Dm', ripetizioni: 8 }),
      P('l4-la7', 'accordo',
        'La settima',
        'Un dito, l\'indice su C-1. Costa niente e apre la porta a Re e Re minore.',
        'Suonarlo pulito 8 volte di fila',
        { accordo: 'A7', ripetizioni: 8 }),
      P('l4-mi7', 'accordo',
        'Mi settima',
        'Indice G-1, medio C-2, e il mignolo (o l\'anulare) su A-2. È l\'accordo che porta a casa in La minore.',
        'Suonarlo pulito 8 volte di fila',
        { accordo: 'E7', ripetizioni: 8 }),
      P('l4-cambio-amdm', 'cambio',
        'Cambio La minore ↔ Re minore',
        'Il medio resta sulla G: pensa a "aggiungo due dita", non a "cambio accordo".',
        '16 battute a 66 bpm',
        { accordi: ['Am', 'Dm'], bpm: 66, battute: 16 }),
      P('l4-cambio-dme7', 'cambio',
        'Cambio Re minore ↔ Mi settima',
        'Due forme vicine ma con dita diverse. È il cambio che fa suonare "italiano" un giro.',
        '16 battute a 60 bpm',
        { accordi: ['Dm', 'E7'], bpm: 60, battute: 16 }),
      P('l4-giro-minore', 'giro',
        'Giro in La minore',
        'La minore · Re minore · Mi settima. Stessa mano, umore opposto.',
        'Il giro intero senza fermarti',
        { brano: 'giro-am-dm', bpm: 72 }),
      P('l4-bellaciao', 'giro',
        'Bella ciao',
        'Il primo brano in tonalità minore. Va veloce: parti a 80 e sali.',
        'Suonarla dall\'inizio alla fine',
        { brano: 'bella-ciao', bpm: 96 }),
      P('l4-mim', 'accordo',
        'Mi minore',
        'Una scaletta diagonale: indice A-2, medio E-3, anulare C-4. Le dita vanno messe una alla volta partendo dall\'indice.',
        'Suonarlo pulito 8 volte di fila',
        { accordo: 'Em', ripetizioni: 8 }),
      P('l4-orecchio', 'orecchio',
        'Riconosci l\'accordo fra tre',
        'Ora la scelta è fra tre accordi veri, non fra due categorie. Serve a costruire la memoria del suono: quando la avrai, imparerai le canzoni molto più in fretta.',
        '6 risposte esatte',
        { modo: 'quale', opzioni: ['C', 'F', 'G', 'Am', 'Dm', 'E7'], scelte: 3, corrette: 6 }),
      P('l4-chunk', 'ritmo',
        'Il "chunk": lo stop col palmo',
        'Sul 2 e sul 4 la mano penna e nello stesso istante il palmo appoggia sulle corde: esce un colpo secco invece di una nota. È quello che trasforma una strimpellata in un groove.',
        '16 battute a 76 bpm',
        { ritmo: 'r-chunk', accordo: 'Am', bpm: 76, battute: 16 }),
      P('l4-50s', 'giro',
        'Giro anni \'50',
        'Do · La minore · Fa · Sol: quattro accordi che sai già, in ordine nuovo.',
        'Il giro intero senza fermarti',
        { brano: 'giro-50s', bpm: 78 }),
      P('l4-aura-lee', 'giro',
        'Aura Lee',
        'Do, La minore, Re minore, Sol settima: la melodia che Elvis avrebbe riusato un secolo dopo.',
        'Suonarla dall\'inizio alla fine',
        { brano: 'aura-lee', bpm: 82 }),
      P('l4-michael', 'giro',
        'Michael Row the Boat Ashore',
        'Cinque accordi diversi in otto battute: è il ripasso di tutto il livello.',
        'Suonarla dall\'inizio alla fine',
        { brano: 'michael-row', bpm: 88 }),
    ],
  },

  {
    id: 'l5',
    nome: 'Livello 5 — Tre quarti, barré, altre tonalità',
    sottotitolo: 'Contare a tre, stendere un dito su più corde, e uscire dal Do',
    passi: [
      P('l5-valzer', 'ritmo',
        'Il valzer: contare a tre',
        'Tre battiti per battuta invece di quattro. Sembra un dettaglio e non lo è: il corpo conta a quattro da solo, a tre bisogna volerlo.',
        '16 battute a 84 bpm',
        { ritmo: 'r-valzer', accordo: 'C', bpm: 84, battute: 16 }),
      P('l5-do7', 'accordo',
        'Do settima',
        'Come il Do ma un dito solo al 1° tasto della A. Serve a spingere verso il Fa.',
        'Suonarlo pulito 8 volte di fila',
        { accordo: 'C7', ripetizioni: 8 }),
      P('l5-amazing', 'giro',
        'Amazing Grace',
        'Valzer con Do, Do settima e Fa. Lento: ogni cambio sporco si sente.',
        'Suonarla dall\'inizio alla fine',
        { brano: 'amazing-grace', bpm: 80 }),
      P('l5-tanti-auguri', 'giro',
        'Tanti auguri a te',
        'Serve più di quanto pensi, ed è in tre quarti. Impararla adesso è un investimento sociale.',
        'Suonarla dall\'inizio alla fine',
        { brano: 'tanti-auguri', bpm: 92 }),
      P('l5-re', 'accordo',
        'Re maggiore',
        'Tre dita sullo STESSO tasto: se non ci stanno tutte, mettile in diagonale (indice più vicino al capotasto) oppure stendi l\'indice a coprire due corde. Nessuna delle due è barare.',
        'Suonarlo pulito 8 volte di fila',
        { accordo: 'D', ripetizioni: 8 }),
      P('l5-cambio-gd', 'cambio',
        'Cambio Sol ↔ Re',
        'Il cambio più comune quando si esce dalla tonalità di Do. Entrambi occupano tre dita: conviene pensarli come due forme intere, non come sei dita da spostare.',
        '16 battute a 62 bpm',
        { accordi: ['G', 'D'], bpm: 62, battute: 16 }),
      P('l5-doowop', 'giro',
        'Doo-wop in Sol',
        'Lo stesso giro anni \'50, ma in Sol: serve a staccare la mano dall\'abitudine del Do.',
        'Il giro intero senza fermarti',
        { brano: 'giro-doowop-sol', bpm: 76 }),
      P('l5-rising', 'giro',
        'House of the Rising Sun',
        'Valzer che chiede il Re maggiore e il Fa in sequenza. È la prova del nove della mano sinistra.',
        'Suonarla dall\'inizio alla fine',
        { brano: 'rising-sun', bpm: 72 }),
      P('l5-sib', 'accordo',
        'Sib maggiore — il primo mezzo barré',
        'L\'indice si stende di lato (non di punta!) a coprire E e A al 1° tasto, il medio va su C-2 e l\'anulare su G-3. Usa il lato osseo del dito, non il polpastrello morbido: preme meglio con meno forza.',
        'Suonarlo pulito 8 volte di fila',
        { accordo: 'Bb', ripetizioni: 8 }),
      P('l5-ascolta-sib', 'ascolta',
        'Il microfono controlla il tuo Sib',
        'Il barré è il posto dove l\'autoinganno costa di più: si sente un accordo, sembra giusto, e invece una corda è mezza spenta. Qui si vede nero su bianco quale.',
        '4 accordi riconosciuti come corretti',
        { accordo: 'Bb', corretti: 4 }),
      P('l5-si7', 'accordo',
        'Si settima',
        'Indice steso al 2° tasto su tutte e quattro, anulare sopra sulla C al 3°. Il barré pieno: se ronza una corda, ruota il dito verso il capotasto.',
        'Suonarlo pulito 8 volte di fila',
        { accordo: 'B7', ripetizioni: 8 }),
      P('l5-trasporto', 'lettura',
        'Cambiare tonalità senza reimparare niente',
        '',
        'Risposta esatta alla domanda',
        {
          punti: [
            'Un giro è fatto di NUMERI, non di nomi: I–V–vi–IV in Do è Do·Sol·Lam·Fa, in Sol è Sol·Re·Mim·Do.',
            'Trasportare serve quasi sempre per la voce: se una canzone è troppo alta per te, spostala di due o tre semitoni in giù e resta la stessa canzone.',
            'Sull\'ukulele ogni tasto è un semitono: alzare tutto di un tasto significa alzare la tonalità di un semitono.',
            'Nella schermata di un giro c\'è il comando "trasporta": cambia i nomi degli accordi e ti mostra i nuovi diagrammi.',
            'Le tonalità comode sull\'ukulele sono Do, Fa, Sol e La minore: sono quelle che usano le corde libere.',
          ],
          quiz: [{
            d: 'Vuoi suonare il giro Do·Sol·Lam·Fa due semitoni più su. Cosa diventa?',
            opzioni: ['Re·La·Sim·Sol', 'Mi·Si·Do♯m·La', 'Do♯·Sol♯·La♯m·Fa♯'],
            giusta: 0,
            perche: 'Due semitoni sopra Do c\'è Re, sopra Sol c\'è La, sopra La minore c\'è Si minore, sopra Fa c\'è Sol. Tutti gli accordi si spostano della stessa quantità: è questo che li tiene insieme.',
          }],
        }),
      P('l5-greensleeves', 'giro',
        'Greensleeves',
        'Valzer inglese del Cinquecento: La minore, Sol e Mi settima. Molto lento, molto esposto.',
        'Suonarla dall\'inizio alla fine',
        { brano: 'greensleeves', bpm: 88 }),
      P('l5-scarborough', 'giro',
        'Scarborough Fair',
        'Valzer lentissimo in minore. Serve a controllare che i cambi siano puliti, non veloci.',
        'Suonarla dall\'inizio alla fine',
        { brano: 'scarborough', bpm: 76 }),
    ],
  },

  {
    id: 'l6',
    nome: 'Livello 6 — Shuffle, blues, velocità',
    sottotitolo: 'Quando il tempo non è più diviso in due',
    passi: [
      P('l6-shuffle', 'ritmo',
        'Lo shuffle: il battito diviso in tre',
        'Fino a ora ogni battito valeva due caselle. Qui ne vale tre e tu suoni la prima e la terza: lungo-corto, lungo-corto. Non si ottiene suonando più veloce, si ottiene contando diverso.',
        '16 battute a 76 bpm',
        { ritmo: 'r-shuffle', accordo: 'C7', bpm: 76, battute: 16 }),
      P('l6-fa7', 'accordo',
        'Fa settima',
        'Quattro dita, la prima forma davvero "da adulti". Serve per il blues.',
        'Suonarlo pulito 8 volte di fila',
        { accordo: 'F7', ripetizioni: 8 }),
      P('l6-blues', 'giro',
        'Blues di 12 battute in Do',
        'Do7, Fa7, Sol7 in una forma fissa di dodici battute che si ripete. Da qui non si esce più. Suonalo con lo shuffle.',
        'Due giri interi di seguito',
        { brano: 'blues-do', bpm: 80, battute: 24 }),
      P('l6-re7', 'accordo',
        'Re settima (versione facile)',
        'Due dita: indice G-2, medio E-2. La versione a barré esiste, ma questa suona bene e ti serve subito per il blues in Sol.',
        'Suonarlo pulito 8 volte di fila',
        { accordo: 'D7-facile', ripetizioni: 8 }),
      P('l6-blues-sol', 'giro',
        'Blues di 12 battute in Sol',
        'La stessa forma, altra tonalità. Se ti accorgi che stai suonando "la stessa cosa" con nomi diversi, hai capito i gradi.',
        'Un giro intero',
        { brano: 'blues-sol', bpm: 84 }),
      P('l6-reggae', 'ritmo',
        'Reggae: suonare solo i controtempi',
        'Sui battiti pieni non suoni niente, solo sulle "e". Conta a voce alta "1 e 2 e 3 e 4 e" e penna solo sulle e. Il silenzio sul battito è la cosa difficile.',
        '16 battute a 76 bpm',
        { ritmo: 'r-reggae', accordo: 'Am', bpm: 76, battute: 16 }),
      P('l6-dm7', 'accordo',
        'Re minore settima',
        'Quattro dita ma comodissime. È metà del giro più usato del jazz.',
        'Suonarlo pulito 8 volte di fila',
        { accordo: 'Dm7', ripetizioni: 8 }),
      P('l6-cmaj7', 'accordo',
        'Do maggiore settima',
        'Un dito solo, al 2° tasto della A. Il suono "sospeso e morbido" che senti nelle sigle e nelle bossa nova.',
        'Suonarlo pulito 8 volte di fila',
        { accordo: 'Cmaj7', ripetizioni: 8 }),
      P('l6-ii-v-i', 'giro',
        'ii–V–I: il giro del jazz',
        'Re minore settima · Sol settima · Do maggiore settima. Tre accordi che si passano la palla e chiudono: da qui parte tutto il repertorio standard.',
        'Il giro intero senza fermarti',
        { brano: 'giro-ii-v-i', bpm: 72 }),
      P('l6-orecchio', 'orecchio',
        'Settima o no?',
        'La settima di dominante è la nota che crea la voglia di andare da qualche parte. Impararla a orecchio significa capire dove sta andando una canzone mentre la ascolti.',
        '6 risposte esatte',
        { modo: 'quale', opzioni: ['C', 'C7', 'G', 'G7', 'F', 'F7'], scelte: 2, corrette: 6 }),
      P('l6-canone', 'giro',
        'Il giro del Canone',
        'Otto battute che si richiudono da sole. Vecchie di trecentocinquant\'anni e ancora dappertutto.',
        'Il giro intero senza fermarti',
        { brano: 'giro-canone', bpm: 74 }),
      P('l6-andaluso', 'giro',
        'Giro andaluso',
        'La minore · Sol · Fa · Mi settima. Scende e resta in tensione: si può girare per dieci minuti.',
        'Il giro intero senza fermarti',
        { brano: 'giro-andaluso', bpm: 74 }),
      P('l6-labamba', 'giro',
        'La Bamba',
        'Tre accordi in cerchio a velocità sostenuta. Se regge questa, la mano destra c\'è.',
        'Suonarla a 96 bpm',
        { brano: 'la-bamba', bpm: 96 }),
      P('l6-misto', 'cambio',
        'Cambi a sorteggio',
        'Il programma pesca fra tutti gli accordi che hai studiato e te li mette davanti senza preavviso. È la differenza fra sapere gli accordi e saperli usare.',
        '24 battute a 76 bpm',
        { accordi: 'appresi', bpm: 76, battute: 24 }),
      P('l6-veloce', 'cambio',
        'Do · Fa · Sol a velocità',
        'Gli stessi tre accordi del secondo mese, ma a 100 bpm. La velocità arriva dal fatto che le dita partono prima, non che si muovono più in fretta. Prova con l\'aumento automatico acceso.',
        '16 battute a 100 bpm',
        { accordi: ['C', 'F', 'G'], bpm: 100, battute: 16, salita: 4 }),
    ],
  },

  {
    id: 'l7',
    nome: 'Livello 7 — Le dita: arpeggi e indipendenza',
    sottotitolo: 'La mano destra smette di spazzolare e comincia a scegliere',
    passi: [
      P('l7-dita', 'lettura',
        'Una corda per dito',
        '',
        'Risposta esatta alla domanda',
        {
          punti: [
            'Nell\'arpeggio ogni dito della mano destra ha la SUA corda e non la cambia: p (pollice) sulla G, i (indice) sulla C, m (medio) sulla E, a (anulare) sulla A.',
            'Le lettere vengono dallo spagnolo — pulgar, índice, medio, anular — ed è la notazione usata da tutta la letteratura per chitarra classica.',
            'Il pollice suona verso il basso (spinge), le altre dita verso l\'alto (tirano). Il movimento è delle dita, non del polso: il polso sta fermo.',
            'La mano si appoggia con l\'avambraccio sul bordo della cassa; non poggiare il mignolo sulla tavola, blocca il movimento.',
            'La regola una-corda-per-dito è quella che rende l\'arpeggio automatico: se le dita non devono decidere dove andare, la testa è libera di pensare agli accordi.',
          ],
          quiz: [{
            d: 'Nell\'arpeggio p-i-m-a, quale dito suona la corda E?',
            opzioni: ['Il pollice (p)', 'L\'indice (i)', 'Il medio (m)'],
            giusta: 2,
            perche: 'Le corde in ordine G C E A prendono rispettivamente p, i, m, a. La E è la terza, quindi tocca al medio.',
          }],
        }),
      P('l7-pima', 'ritmo',
        'Arpeggio p-i-m-a',
        'Il primo arpeggio: sale dalla G alla A e ricomincia. Tieni un Do premuto e non pensare alla mano sinistra. Lentissimo — la velocità qui non serve a niente.',
        '16 battute a 60 bpm',
        { ritmo: 'a-pima', accordo: 'C', bpm: 60, battute: 16 }),
      P('l7-pami', 'ritmo',
        'Arpeggio p-a-m-i',
        'Come prima ma la parte alta scende invece di salire. Suona più dolce perché finisce vicino al grave.',
        '16 battute a 64 bpm',
        { ritmo: 'a-pami', accordo: 'Am', bpm: 64, battute: 16 }),
      P('l7-pizzico', 'ritmo',
        'Pizzico e arpeggio',
        'Sul battito pollice e anulare pizzicano insieme le due corde esterne, poi le due di mezzo riempiono. È l\'accompagnamento di metà delle ballate mai scritte.',
        '16 battute a 66 bpm',
        { ritmo: 'a-pizzico', accordo: 'F', bpm: 66, battute: 16 }),
      P('l7-ninna', 'giro',
        'Ninna nanna di Brahms — ad arpeggio',
        'Lentissima e in tre quarti: il posto giusto per usare l\'arpeggio invece della pennata. Suonala con lo schema p-i-m-a e ascolta la differenza.',
        'Suonarla dall\'inizio alla fine',
        { brano: 'ninna-nanna', bpm: 72 }),
      P('l7-valzer-arp', 'ritmo',
        'Arpeggio da valzer',
        'Basso sul primo battito, poi le dita salgono. Tre quarti col pollice che tiene il tempo.',
        '16 battute a 76 bpm',
        { ritmo: 'a-valzer', accordo: 'C', bpm: 76, battute: 16 }),
      P('l7-santa-lucia', 'giro',
        'Santa Lucia — ad arpeggio',
        'Barcarola del 1849, tre quarti larghi. Provala con l\'arpeggio da valzer.',
        'Suonarla dall\'inizio alla fine',
        { brano: 'santa-lucia', bpm: 84 }),
      P('l7-alternato', 'ritmo',
        'Pollice alternato',
        'Il pollice tiene il passo mentre le altre dita fanno qualcos\'altro. È vera indipendenza fra le due metà della mano: parti a 50 bpm e non vergognartene.',
        '16 battute a 58 bpm',
        { ritmo: 'a-alternato', accordo: 'C', bpm: 58, battute: 16 }),
      P('l7-sei-otto', 'ritmo',
        'Sei ottavi',
        'Due battiti grandi, ognuno diviso in tre. È il dondolio delle ninne nanne e di metà del folk irlandese.',
        '16 battute a 66 bpm',
        { ritmo: 'r-sei-otto', accordo: 'Am', bpm: 66, battute: 16 }),
      P('l7-pop-minore', 'giro',
        'Giro pop in minore',
        'Gli ultimi quattro accordi, questa volta partendo dal minore. Scegli tu se pennare o arpeggiare: da qui in poi è una decisione tua.',
        'Il giro intero senza fermarti',
        { brano: 'giro-pop-minore', bpm: 76 }),
      P('l7-tutto', 'cambio',
        'Tutti gli accordi, a sorteggio, a velocità',
        'L\'esame finale: tutto quello che hai imparato, mescolato, a 88 bpm. Se lo reggi, non stai più imparando gli accordi — li stai usando.',
        '32 battute a 88 bpm',
        { accordi: 'appresi', bpm: 88, battute: 32, salita: 2 }),
    ],
  },
];

export const PASSI = LIVELLI.flatMap((l) => l.passi.map((p) => ({ ...p, livello: l.id })));
export const PER_ID = new Map(PASSI.map((p) => [p.id, p]));

export function passo(id) {
  return PER_ID.get(id) || null;
}

/** Accordi introdotti dal percorso fino a un certo passo (compreso). */
export function accordiFinoA(idPasso) {
  const fine = PASSI.findIndex((p) => p.id === idPasso);
  const entro = fine < 0 ? PASSI : PASSI.slice(0, fine + 1);
  const visti = [];
  entro.forEach((p) => {
    if (p.tipo === 'accordo' && !visti.includes(p.dati.accordo)) visti.push(p.dati.accordo);
  });
  return visti;
}

/** Accordi che l'utente ha già segnato come fatti: alimenta i "cambi a sorteggio". */
export function accordiAppresi(passiFatti) {
  const visti = PASSI
    .filter((p) => p.tipo === 'accordo' && passiFatti[p.id])
    .map((p) => p.dati.accordo);
  return visti.length >= 2 ? visti : ['C', 'Am', 'F'];
}

/** Il prossimo passo non fatto: è la risposta a "che faccio oggi?". */
export function prossimoPasso(passiFatti) {
  return PASSI.find((p) => !passiFatti[p.id]) || null;
}

export function avanzamentoLivello(livello, passiFatti) {
  const fatti = livello.passi.filter((p) => passiFatti[p.id]).length;
  return { fatti, totale: livello.passi.length, quota: fatti / livello.passi.length };
}
