// Il percorso: cosa studiare, in quale ordine, e come sapere di averlo fatto.
//
// Criterio dell'ordine: ogni passo aggiunge UNA difficoltà sola. Un accordo nuovo non
// arriva insieme a un ritmo nuovo, e un ritmo nuovo si prova su un accordo che le dita
// già conoscono.
//
// ── Perché questo ordine e non quello dell'ukulele ────────────────────────────
//
// Sull'ukulele si parte dal Do, che è un dito solo, e il muro non c'è: il pezzo più duro
// del primo anno è il Mi. Sulla chitarra la mappa è un'altra e va rispettata, altrimenti
// si insegna a mollare:
//
//   Si parte dal MI MINORE, non dal Do. Due dita, tutte e sei le corde suonano, non c'è
//   niente da smorzare. Il Do arriva al terzo livello perché chiede tre dita in diagonale
//   E la 6ª corda da non suonare: sono due difficoltà insieme.
//
//   Le corde SMORZATE sono un argomento, non una nota a piè di pagina. Sull'ukulele erano
//   un'eccezione rara; qui metà libreria ha una ✕, e suonare il Mi basso su un Do lo
//   trasforma in un'altra cosa senza che chi impara se ne accorga.
//
//   Il BARRÉ ha un livello suo. È il muro del secondo mese, quello dove si smette: non si
//   attraversa con un passo fra gli altri, ma con una scaletta di mezzi barré, un ordine
//   dal più facile al più duro (Fa♯m prima del Fa, non dopo) e degli esercizi che parlano
//   di polso e di pollice invece che di forza.
//
//   Il FINGERPICKING pesa il doppio. Il pollice alternato e il Travis non sono un livello
//   avanzato: sono il suono della chitarra acustica, e ci si arriva prima del barré.
//
// L'ordine non è un'opinione: `collaudo.html` verifica che nessun passo chieda un accordo
// non ancora introdotto. Le eccezioni esistono ma vanno DICHIARATE in `dati.tollera`,
// così una scorciatoia didattica resta una scelta e non diventa una svista.
//
// Tipi di passo:
//   accordatura — apre l'accordatore, si chiude da sé quando le sei corde sono a posto
//   lettura     — una scheda da leggere, con domanda di controllo
//   accordo     — la forma nuova: la premi, la suoni, la togli, la rimetti
//   ascolta     — il microfono verifica che l'accordo suoni davvero come deve
//   orecchio    — allenamento dell'orecchio: riconoscere senza guardare
//   cambio      — l'esercizio che fa la differenza: due accordi a tempo di metronomo
//   ritmo       — mano destra sul telaio del ritmo (pennata o arpeggio)
//   giro        — suonare un giro o un brano dall'inizio alla fine

const P = (id, tipo, titolo, testo, obiettivo, dati = {}) =>
  ({ id, tipo, titolo, testo, obiettivo, dati });

export const LIVELLI = [
  {
    id: 'l0',
    nome: 'Livello 0 — Prima di suonare',
    sottotitolo: 'Strumento accordato, le due mani, e come si legge un diagramma',
    passi: [
      P('l0-accorda', 'accordatura',
        'Accorda le sei corde',
        'Uno strumento scordato insegna l\'intonazione sbagliata: l\'orecchio impara quello che sente. Prima di ogni sessione, un minuto qui. Le corde nuove calano per giorni: non è colpa tua.',
        'Tutte e sei le corde entro 5 centesimi',
        {}),
      P('l0-mani', 'lettura',
        'Come si tiene, come si preme, come si penna',
        '',
        'Risposta esatta alla domanda',
        {
          punti: [
            'La chitarra si appoggia sulla gamba destra (o sulla sinistra, più in alto, come fanno i classici: si fa meno fatica). La cassa contro il petto. La mano sinistra NON la regge: deve essere libera di andarsene in giro.',
            'Mano sinistra: pollice dietro il manico, più o meno all\'altezza del dito medio e verso il centro, non affacciato sopra il bordo. Dita curve, unghie corte.',
            'Si preme con la PUNTA del dito, subito dietro la barretta di metallo e non sopra: lì la corda si ferma da sola e serve pochissima forza. A metà tasto devi schiacciare il triplo e la nota esce sorda lo stesso.',
            'Mano destra: si penna sopra la buca o poco più indietro. Vicino al ponte il suono diventa nasale, sopra la tastiera diventa molle.',
            'Se una corda ronza, nove volte su dieci il dito è lontano dalla barretta o sta toccando anche la corda accanto. Non è forza che manca: è posizione.',
            'Le unghie della mano sinistra vanno corte davvero. Con le unghie lunghe il polpastrello non arriva sulla corda e nessuna quantità di forza rimedia.',
          ],
          quiz: [{
            d: 'Dove va la punta del dito quando premi un tasto?',
            opzioni: ['Sopra la barretta di metallo', 'Subito dietro la barretta, verso la cassa', 'A metà fra due barrette'],
            giusta: 1,
            perche: 'Premendo subito dietro la barretta la corda si ferma esattamente lì e serve poca forza. A metà tasto la nota esce sorda e devi schiacciare il triplo.',
          }],
        }),
      P('l0-diagramma', 'lettura',
        'Leggere un diagramma di accordo',
        '',
        'Risposta esatta alla domanda',
        {
          punti: [
            'Il manico è disegnato in verticale, come se guardassi la chitarra di fronte con la paletta in alto.',
            'Le sei linee verticali sono le corde. Da SINISTRA a destra: Mi La Re Sol Si Mi — cioè dalla 6ª (la più grossa e grave) alla 1ª (il cantino). Le due esterne sono entrambe Mi, a due ottave di distanza.',
            'La linea spessa in alto è il capotasto. Le linee orizzontali sotto sono i tasti.',
            'Un pallino dice dove premere; il numero dentro è il dito (1 indice, 2 medio, 3 anulare, 4 mignolo).',
            'Un cerchio vuoto sopra il capotasto = corda da suonare libera. Una ✕ = corda da NON far suonare. Sulla chitarra la ✕ è normale e va presa sul serio: metà degli accordi ne ha una.',
            'Una capsula lunga = un dito solo che preme più corde insieme. Si chiama barré, e per ora ti basta sapere che esiste.',
            'Se in alto a sinistra c\'è scritto "5fr", il diagramma non parte dal capotasto ma dal 5° tasto.',
          ],
          quiz: [{
            d: 'Nel diagramma c\'è una ✕ sopra la corda più a sinistra. Cosa vuol dire?',
            opzioni: ['Che quella corda va premuta forte', 'Che quella corda non deve suonare: la pennata parte da quella dopo', 'Che è un errore di stampa'],
            giusta: 1,
            perche: 'La ✕ dice "questa corda sta zitta". Suonare il Mi basso su un Do non lo rende più pieno: lo trasforma in un altro accordo, e chi impara non se ne accorge da solo.',
          }],
        }),
      P('l0-pennata', 'ritmo',
        'Quattro pennate a vuoto',
        'Senza premere niente: solo la mano destra e il metronomo. Serve a far combaciare il tuo tempo con un tempo esterno, che è la cosa più difficile di tutte e non c\'entra con le dita.',
        '16 battute a 70 bpm senza perdere il tempo',
        { ritmo: 'r-giu4', accordo: null, bpm: 70, battute: 16 }),
    ],
  },

  {
    id: 'l1',
    nome: 'Livello 1 — Due dita, e sei dentro',
    sottotitolo: 'Mi minore e La minore: la stessa forma, spostata di una corda',
    passi: [
      P('l1-mim', 'accordo',
        'Mi minore',
        'Medio e anulare al 2° tasto, sulla 5ª e sulla 4ª corda. Poi penna TUTTE e sei le corde. Non c\'è niente da smorzare, niente da evitare: è l\'accordo più generoso della chitarra, e il primo che si impara da sempre.',
        'Suonarlo pulito 8 volte di fila',
        { accordo: 'Em', ripetizioni: 8 }),
      P('l1-ascolta-mim', 'ascolta',
        'Il microfono controlla il Mi minore',
        'Penna e lascia suonare. Il programma ti dice quale corda non sta uscendo. Un paio di corde saranno segnate "–": suonano la stessa nota di un\'altra e nessun programma può giudicarle separatamente. È fisica, non pigrizia.',
        '4 accordi riconosciuti come corretti',
        { accordo: 'Em', corretti: 4 }),
      P('l1-lam', 'accordo',
        'La minore',
        'La stessa forma del Mi minore spostata di una corda verso il basso, più l\'indice al 1° tasto della 2ª. E qui arriva la prima ✕: il Mi basso non si suona, la pennata parte dalla 5ª corda. Se ti scappa, non è un La minore.',
        'Suonarlo pulito 8 volte di fila',
        { accordo: 'Am', ripetizioni: 8 }),
      P('l1-cambio', 'cambio',
        'Cambio Mi minore ↔ La minore',
        'Qui si impara davvero. Il segreto non è la velocità delle dita ma ANTICIPARE: la mano sinistra deve partire mentre la destra suona l\'ultima pennata della battuta, non dopo. Medio e anulare restano nella stessa forma: pensala come un blocco unico che trasloca.',
        '16 battute a 60 bpm',
        { accordi: ['Em', 'Am'], bpm: 60, battute: 16 }),
      P('l1-ritmo', 'ritmo',
        'Otto pennate su un accordo',
        'Giù-su continuo, senza fermarsi mai. Tieni il Mi minore premuto e pensa solo al polso: il movimento parte da lì, non dal gomito.',
        '16 battute a 70 bpm',
        { ritmo: 'r-otto', accordo: 'Em', bpm: 70, battute: 16 }),
      P('l1-giro', 'giro',
        'Il tuo primo giro',
        'Due battute di Mi minore, due di La minore. Un accordo ogni quattro pennate: tutto il tempo del mondo per spostare la mano.',
        'Il giro intero senza fermarti',
        { brano: 'giro-em-am', bpm: 62 }),
    ],
  },

  {
    id: 'l2',
    nome: 'Livello 2 — Il Sol e il Re',
    sottotitolo: 'La mano si apre, e arriva la prima canzone vera',
    passi: [
      P('l2-accorda', 'accordatura',
        'Ricontrolla l\'accordatura',
        'Le corde nuove calano per settimane, e la 3ª (Sol) è quella che scappa per prima. Trenta secondi.',
        'Tutte e sei le corde entro 5 centesimi',
        {}),
      P('l2-re', 'accordo',
        'Re maggiore',
        'Un triangolino sulle tre corde acute: indice sulla 3ª, medio sulla 1ª, anulare sulla 2ª. Suonano solo quattro corde — la 6ª e la 5ª restano zitte. È il primo accordo dove devi tenere a mente da dove parte la pennata.',
        'Suonarlo pulito 8 volte di fila',
        { accordo: 'D', ripetizioni: 8 }),
      P('l2-cambio-emd', 'cambio',
        'Cambio Mi minore ↔ Re',
        'Due accordi lontani: le dita devono staccarsi tutte e riatterrare insieme. Non provare ad andare veloce — prova ad arrivare TUTTE nello stesso istante, anche lentissimo.',
        '16 battute a 60 bpm',
        { accordi: ['Em', 'D'], bpm: 60, battute: 16 }),
      P('l2-sol', 'accordo',
        'Sol maggiore',
        'La mano si apre davvero: medio sulla 6ª al 3° tasto, indice sulla 5ª al 2°, anulare sulla 1ª al 3°. Tre dita distanti fra loro e tutte e sei le corde che suonano. All\'inizio sembra impossibile e in una settimana diventa automatico.',
        'Suonarlo pulito 8 volte di fila',
        { accordo: 'G', ripetizioni: 8 }),
      P('l2-ascolta-sol', 'ascolta',
        'Il microfono controlla il Sol',
        'Nel Sol le corde di mezzo sono libere: se una non suona è perché un dito la sta sfiorando. È l\'errore più comune di questo accordo, e a orecchio non si sente finché non te lo dicono.',
        '4 accordi riconosciuti come corretti',
        { accordo: 'G', corretti: 4 }),
      P('l2-cambio-gd', 'cambio',
        'Cambio Sol ↔ Re',
        'Il cambio più usato della musica per chitarra. Cerca il "dito guida": l\'anulare resta sul 3° tasto della 1ª corda? No — ma il medio e l\'anulare si scambiano di posto in modo regolare. Guarda le tue mani e trova il tuo.',
        '16 battute a 66 bpm',
        { accordi: ['G', 'D'], bpm: 66, battute: 16 }),
      P('l2-re7', 'accordo',
        'Re settima',
        'Un triangolo capovolto rispetto al Re. Non è un accordo "difficile in più": è quello che chiude le frasi. Dopo un Re settima l\'orecchio PRETENDE un Sol, e sentirlo da soli è il primo momento in cui la teoria diventa musica.',
        'Suonarlo pulito 8 volte di fila',
        { accordo: 'D7', ripetizioni: 8 }),
      P('l2-cambio-gd7', 'cambio',
        'Cambio Sol ↔ Re settima',
        'Lo stesso cambio di prima ma con la settima: cambia un dito solo rispetto al Re, e cambia tutto quello che senti.',
        '16 battute a 66 bpm',
        { accordi: ['G', 'D7'], bpm: 66, battute: 16 }),
      P('l2-ritmo-classico', 'ritmo',
        'Il ritmo classico (giù, giù-su, su-giù-su)',
        'Il ritmo più usato al mondo. Regola unica: la mano NON si ferma mai, nemmeno nei buchi — ci passa sopra senza toccare le corde. Se la fermi, il tempo si perde e non torna.',
        '16 battute a 70 bpm',
        { ritmo: 'r-classico', accordo: 'Em', bpm: 70, battute: 16 }),
      P('l2-giro', 'giro',
        'Giro Sol · Re',
        'Due accordi, due battute ciascuno. Suonalo finché non devi più guardare la mano sinistra.',
        'Il giro intero senza fermarti',
        { brano: 'giro-g-d', bpm: 68 }),
      P('l2-fra', 'giro',
        'Fra Martino campanaro',
        'La prima canzone vera, e la sai già a memoria: questo è il punto. Sette battute di Sol e una di Re settima.',
        'Suonarla dall\'inizio alla fine',
        { brano: 'fra-martino', bpm: 84 }),
      P('l2-susanna', 'giro',
        'Oh Susanna',
        'Stessi due accordi, ma i cambi arrivano più spesso e il tempo è più svelto. È il salto di difficoltà giusto: niente di nuovo da imparare, solo da fare meglio.',
        'Suonarla dall\'inizio alla fine',
        { brano: 'oh-susanna', bpm: 92 }),
      P('l2-cielito', 'giro',
        'Cielito lindo',
        'Il primo tre quarti: UN-due-tre, UN-due-tre. Conta a voce alta, davvero. Il valzer non si sente finché non lo si conta.',
        'Suonarla dall\'inizio alla fine',
        { brano: 'cielito-lindo', bpm: 88 }),
    ],
  },

  {
    id: 'l3',
    nome: 'Livello 3 — Il Do, e le corde che non devono suonare',
    sottotitolo: 'Quattro accordi, e con quelli si accompagna mezzo mondo',
    passi: [
      P('l3-do', 'accordo',
        'Do maggiore',
        'Una diagonale: anulare sulla 5ª al 3°, medio sulla 4ª al 2°, indice sulla 2ª al 1°. Le dita scendono a scaletta e il Mi basso non si suona. Se ti scappa la 6ª esce un Do con il Mi sotto: suona, ma non è la stessa cosa.',
        'Suonarlo pulito 8 volte di fila',
        { accordo: 'C', ripetizioni: 8 }),
      P('l3-smorzare', 'lettura',
        'Come si fa a NON suonare una corda',
        '',
        'Risposta esatta alla domanda',
        {
          punti: [
            'Primo modo, quello onesto: la pennata parte dalla corda giusta. Sul Do parti dalla 5ª, sul Re dalla 4ª. Costa attenzione e all\'inizio rallenta, ma è il modo pulito.',
            'Secondo modo, quello che usano tutti: la corda da spegnere la si TOCCA appena con un dito che sta già lì. Sul Do, il polpastrello dell\'anulare che preme la 5ª sfiora anche la 6ª e la spegne. Non la preme: la appoggia.',
            'Terzo modo, quello dei chitarristi di scuola blues: il pollice sinistro spunta sopra il manico e appoggia sulla 6ª. Comodissimo, e chiude la porta ad alcuni accordi più avanti. Va bene lo stesso.',
            'Quando strimpelli forte, mezzo mondo suona tutte e sei le corde e non se ne accorge nessuno. Quando arpeggi con le dita, invece, la corda sbagliata si sente subito: è lì che questa cosa diventa seria.',
            'Il programma nella sezione Ascolta ti dice quali corde stanno suonando davvero. È il modo più rapido per scoprire che stai suonando la 6ª quando credi di no.',
          ],
          quiz: [{
            d: 'Perché sul Do non si suona il Mi basso?',
            opzioni: ['Perché suonerebbe troppo forte', 'Perché quella nota (Mi) non appartiene al Do maggiore e ne cambia il carattere', 'Perché la corda è troppo grossa'],
            giusta: 1,
            perche: 'Il Do maggiore è fatto di Do, Mi e Sol. Il Mi c\'è già, ma metterlo al BASSO cambia l\'accordo: diventa un rivolto, con un\'altra faccia. Non è sbagliato in assoluto — è sbagliato quando volevi un Do.',
          }],
        }),
      P('l3-ascolta-do', 'ascolta',
        'Il microfono controlla il Do',
        'La prova del nove del passo precedente: se stai lasciando suonare il Mi basso, qui si vede.',
        '4 accordi riconosciuti come corretti',
        { accordo: 'C', corretti: 4 }),
      P('l3-cambio-gc', 'cambio',
        'Cambio Sol ↔ Do',
        'Il cambio che si incontra ovunque. Trucco vero: l\'anulare del Sol sta sulla 1ª corda al 3° tasto, quello del Do sulla 5ª al 3°. Stesso tasto, altra corda — lascia che sia lui a guidare il viaggio.',
        '16 battute a 66 bpm',
        { accordi: ['G', 'C'], bpm: 66, battute: 16 }),
      P('l3-cambio-cd', 'cambio',
        'Cambio Do ↔ Re',
        'Due accordi che partono da corde diverse: uno dalla 5ª, l\'altro dalla 4ª. Oltre alle dita, deve spostarsi anche la mano destra.',
        '16 battute a 66 bpm',
        { accordi: ['C', 'D'], bpm: 66, battute: 16 }),
      P('l3-sol7', 'accordo',
        'Sol settima',
        'Il Sol con il cantino che scende dal 3° al 1° tasto. Chiede il Do e non accetta un no: prova a suonare Sol settima e fermarti lì, e senti che la canzone non è finita.',
        'Suonarlo pulito 8 volte di fila',
        { accordo: 'G7', ripetizioni: 8 }),
      P('l3-giro-gcd', 'giro',
        'Giro Sol · Do · Re',
        'I–IV–V: tre accordi con cui si accompagna un secolo di musica popolare. In Sol, perché in Do il terzo grado sarebbe un Fa col barré — e quello arriva molto dopo.',
        'Il giro intero senza fermarti',
        { brano: 'giro-g-c-d', bpm: 72 }),
      P('l3-fattoria', 'giro',
        'Nella vecchia fattoria',
        'Tre accordi e una melodia che sa a memoria chiunque sia stato bambino.',
        'Suonarla dall\'inizio alla fine',
        { brano: 'vecchia-fattoria', bpm: 92 }),
      P('l3-jingle', 'giro',
        'Jingle Bells',
        'Del 1857. È la prima canzone che puoi suonare davanti a qualcuno senza doverlo avvisare.',
        'Suonarla dall\'inizio alla fine',
        { brano: 'jingle-bells', bpm: 100 }),
      P('l3-quattro', 'giro',
        'Il giro dei quattro accordi',
        'Sol, Re, Mi minore, Do. Questo è il giro più redditizio che esista: se cerchi in rete "canzoni con quattro accordi" trovi liste da centinaia di titoli, e sono tutte questo.',
        'Il giro intero senza fermarti',
        { brano: 'giro-quattro', bpm: 74 }),
      P('l3-pop-minore', 'giro',
        'Lo stesso giro, partendo dal minore',
        'Gli stessi quattro accordi in un altro ordine: Mi minore, Do, Sol, Re. Non cambia una posizione e cambia tutto l\'umore. È la lezione più economica della musica.',
        'Il giro intero senza fermarti',
        { brano: 'giro-pop-minore', bpm: 74 }),
      P('l3-auld', 'giro',
        'Auld Lang Syne',
        'La canzone di capodanno. Ha una battuta con DUE accordi: è il primo cambio a metà battuta, e va contato.',
        'Suonarla dall\'inizio alla fine',
        { brano: 'auld-lang-syne', bpm: 82 }),
      P('l3-orecchio', 'orecchio',
        'Allegro o triste?',
        'Il programma suona un accordo, tu dici se è maggiore o minore. Non serve sapere i nomi: serve accorgersi della differenza, che è la prima cosa che un orecchio impara.',
        '6 risposte esatte',
        { modo: 'maggiore-minore', opzioni: ['G', 'Em', 'C', 'Am', 'D'], corrette: 6 }),
    ],
  },

  {
    id: 'l4',
    nome: 'Livello 4 — Le settime e il blues',
    sottotitolo: 'Mi, La, e la forma di dodici battute su cui è costruito il Novecento',
    passi: [
      P('l4-accorda', 'accordatura',
        'Accorda prima di cominciare',
        'Da qui in poi si suona più a lungo e più forte: se lo strumento è scordato lo senti sulle settime prima che altrove.',
        'Tutte e sei le corde entro 5 centesimi',
        {}),
      P('l4-mi', 'accordo',
        'Mi maggiore',
        'Il Mi minore con l\'indice aggiunto al 1° tasto della 3ª corda. Tre dita, sei corde: è l\'accordo più pieno che la chitarra sappia fare, e non a caso quasi tutto il rock parte da qui.',
        'Suonarlo pulito 8 volte di fila',
        { accordo: 'E', ripetizioni: 8 }),
      P('l4-la', 'accordo',
        'La maggiore',
        'Tre dita in fila al 2° tasto, tutte dentro lo stesso spazio. Se non ci stanno, prova a metterle in diagonale invece che allineate — non esiste una sola diteggiatura giusta. Il Mi basso resta fuori.',
        'Suonarlo pulito 8 volte di fila',
        { accordo: 'A', ripetizioni: 8 }),
      P('l4-cambio-ea', 'cambio',
        'Cambio Mi ↔ La',
        'Le stesse tre dita che traslocano di una corda. È il movimento che sta sotto a metà blues.',
        '16 battute a 70 bpm',
        { accordi: ['E', 'A'], bpm: 70, battute: 16 }),
      P('l4-mi7', 'accordo',
        'Mi settima',
        'Il Mi maggiore a cui TOGLI un dito. Due dita, sei corde, e un suono che tira verso il La: è il blues in due dita.',
        'Suonarlo pulito 8 volte di fila',
        { accordo: 'E7', ripetizioni: 8 }),
      P('l4-la7', 'accordo',
        'La settima',
        'Il La a cui togli il dito di mezzo. Porta al Re, ed è il modo più economico di rendere interessante un accompagnamento piatto.',
        'Suonarlo pulito 8 volte di fila',
        { accordo: 'A7', ripetizioni: 8 }),
      P('l4-si7', 'accordo',
        'Si settima',
        'Quattro dita sparpagliate, ma niente barré. Sembra scomodo per una settimana e poi diventa una delle forme che la mano trova da sola. Senza questo il blues in Mi non si chiude.',
        'Suonarlo pulito 8 volte di fila',
        { accordo: 'B7', ripetizioni: 8 }),
      P('l4-ascolta-mi7', 'ascolta',
        'Il microfono controlla il Mi settima',
        'Sul Mi settima la 3ª corda è libera: è quella che le dita vicine spengono senza volere.',
        '4 accordi riconosciuti come corretti',
        { accordo: 'E7', corretti: 4 }),
      P('l4-blues-mi', 'giro',
        'Blues di 12 battute in Mi',
        'La forma più suonata del Novecento, nella tonalità in cui la chitarra la suona da sempre. Dodici battute, tre accordi, e quando arrivi in fondo ricomincia. Suonalo per cinque minuti di fila: è così che si impara a stare dentro una forma.',
        'Dodici battute senza perdere il conto',
        { brano: 'blues-mi', bpm: 76 }),
      P('l4-shuffle', 'ritmo',
        'Lo shuffle (le terzine zoppe)',
        'Il battito si divide in TRE e tu ne suoni la prima e la terza: lungo-corto, lungo-corto. È l\'andatura del blues, e non si ottiene suonando ottavi più svelti — si ottiene contando in tre.',
        '16 battute a 76 bpm',
        { ritmo: 'r-shuffle', accordo: 'E7', bpm: 76, battute: 16 }),
      P('l4-rem', 'accordo',
        'Re minore',
        'Il Re con l\'indice che scende sul cantino. Quattro corde, tre dita: è il minore che serve per suonare in La minore.',
        'Suonarlo pulito 8 volte di fila',
        { accordo: 'Dm', ripetizioni: 8 }),
      P('l4-cambio-amdm', 'cambio',
        'Cambio La minore ↔ Re minore',
        'Due minori vicini di casa. Attenzione a dove parte la pennata: uno dalla 5ª, l\'altro dalla 4ª.',
        '16 battute a 68 bpm',
        { accordi: ['Am', 'Dm'], bpm: 68, battute: 16 }),
      P('l4-bella-ciao', 'giro',
        'Bella ciao',
        'Il primo brano in tonalità minore: La minore, Re minore e Mi settima. Tre accordi che ormai hai tutti.',
        'Suonarla dall\'inizio alla fine',
        { brano: 'bella-ciao', bpm: 96 }),
      P('l4-andaluso', 'giro',
        'Il giro andaluso',
        'Mi minore, Re, Do, Si settima: scende di grado in grado e finisce in tensione. Suona spagnolo perché lo è, ed è un giro che si può ripetere all\'infinito senza annoiare.',
        'Il giro intero senza fermarti',
        { brano: 'giro-andaluso', bpm: 70 }),
      P('l4-greensleeves', 'giro',
        'Greensleeves',
        'Inglese, XVI secolo, in tre quarti. La melodia la conosci di sicuro anche se non sai da dove.',
        'Suonarla dall\'inizio alla fine',
        { brano: 'greensleeves', bpm: 88 }),
      P('l4-50s', 'giro',
        'Giro anni \'50',
        'Sol, Mi minore, Do, Re: doo-wop, ballate da falò, mezzo Elvis. Quattro accordi che sai già tutti, in un ordine nuovo.',
        'Il giro intero senza fermarti',
        { brano: 'giro-50s', bpm: 76 }),
      P('l4-michael', 'giro',
        'Michael Row the Boat Ashore',
        'Cinque accordi diversi in otto battute: è il ripasso di tutto quello che hai imparato finora.',
        'Suonarla dall\'inizio alla fine',
        { brano: 'michael-row', bpm: 86 }),
      P('l4-orecchio', 'orecchio',
        'Che accordo è?',
        'Adesso i nomi servono. Il programma ne suona uno fra tre e tu scegli. Non si indovina: si riconosce il colore, e quello si impara solo sbagliando.',
        '6 risposte esatte',
        { modo: 'quale', opzioni: ['G', 'C', 'D', 'Em', 'Am', 'E7'], scelte: 3, corrette: 6 }),
    ],
  },

  {
    id: 'l5',
    nome: 'Livello 5 — Le dita, non la spazzola',
    sottotitolo: 'Arpeggio, pollice alternato: il suono vero della chitarra acustica',
    passi: [
      P('l5-mano-destra', 'lettura',
        'Le dita della mano destra, e dove sta il basso',
        '',
        'Risposta esatta alla domanda',
        {
          punti: [
            'I nomi vengono dallo spagnolo: p pollice, i indice, m medio, a anulare. Il mignolo non si usa quasi mai.',
            'Le tre dita hanno una corda FISSA e non la lasciano: indice sulla 3ª, medio sulla 2ª, anulare sulla 1ª. Questa regola è quello che rende l\'arpeggio automatico invece che un problema da risolvere ogni volta.',
            'Il pollice invece si prende TRE corde — la 6ª, la 5ª e la 4ª — e ci cammina sopra. Dove va dipende dall\'accordo, ed è la cosa nuova rispetto a qualunque strumento a quattro corde.',
            'Il basso di un accordo è la sua fondamentale: sul Mi e sul Mi minore sta sulla 6ª, sul La e sul La minore sulla 5ª, sul Re e sul Re minore sulla 4ª. Il Sol ha il basso sulla 6ª, il Do sulla 5ª.',
            'Il basso ALTERNATO è la quinta dell\'accordo, e sta quasi sempre due corde più in su. Il pollice va avanti e indietro fra questi due: da lì nasce tutto l\'accompagnamento country e folk.',
            'La mano destra si appoggia? Il polso resta morbido e sospeso, non poggiato sul ponte. Se lo appoggi il suono si smorza e le dita perdono corsa.',
          ],
          quiz: [{
            d: 'Suoni un Re maggiore in arpeggio. Su quale corda va il pollice?',
            opzioni: ['Sulla 6ª, come sempre', 'Sulla 4ª, che è il Re', 'Su quella che capita'],
            giusta: 1,
            perche: 'Il basso è la fondamentale dell\'accordo. Sul Re maggiore la 6ª e la 5ª non si suonano nemmeno: mettere il pollice lì significa suonare un accordo diverso da quello che hai in mano.',
          }],
        }),
      P('l5-pima', 'ritmo',
        'Arpeggio p-i-m-a',
        'Pollice sul basso, poi indice, medio, anulare che salgono. Lento. Il punto non è la velocità: è che ogni dito trovi la SUA corda senza guardare.',
        '16 battute a 60 bpm',
        { ritmo: 'a-pima', accordo: 'Em', bpm: 60, battute: 16 }),
      P('l5-pima-am', 'ritmo',
        'Lo stesso arpeggio sul La minore',
        'Cambia l\'accordo e cambia la corda del pollice: adesso è la 5ª. Le altre tre dita non si spostano di un millimetro. È esattamente la differenza che questo livello vuole insegnare.',
        '16 battute a 60 bpm',
        { ritmo: 'a-pima', accordo: 'Am', bpm: 60, battute: 16 }),
      P('l5-pami', 'ritmo',
        'Arpeggio p-a-m-i',
        'Come il precedente ma torna indietro: sale col pollice e scende. Suona più dolce perché finisce vicino al grave.',
        '16 battute a 64 bpm',
        { ritmo: 'a-pami', accordo: 'C', bpm: 64, battute: 16 }),
      P('l5-ninna', 'giro',
        'Ninna nanna di Brahms',
        'Del 1868, in tre quarti, lentissima. È il brano giusto su cui provare gli arpeggi: se sbagli corda si sente subito, e questo è un vantaggio.',
        'Suonarla dall\'inizio alla fine in arpeggio',
        { brano: 'ninna-nanna', bpm: 70 }),
      P('l5-water', 'giro',
        'The Water Is Wide',
        'Scozzese, XVII secolo. Sedici battute lente e tutte su corde piene: qui l\'arpeggio rende più di qualunque pennata.',
        'Suonarla dall\'inizio alla fine',
        { brano: 'water-is-wide', bpm: 64 }),
      P('l5-basso-alternato', 'ritmo',
        'Il pollice alternato, da solo',
        'Solo il pollice, avanti e indietro fra le due corde del basso. Sembra niente e non lo è: finché questo non cammina da solo — mentre pensi ad altro, mentre parli — il Travis del livello 7 non parte. Fallo per canzoni intere senza aggiungere nient\'altro.',
        '32 battute a 66 bpm',
        { ritmo: 'a-basso-alternato', accordo: 'G', bpm: 66, battute: 32 }),
      P('l5-basso-accordo', 'ritmo',
        'Basso e accordo',
        'Sul 1 e sul 3 suoni SOLO la corda del basso, sul 2 e sul 4 l\'accordo intero. È l\'accompagnamento da falò, e insegna la cosa che serve di più: sapere sempre dov\'è il basso dell\'accordo che stai tenendo.',
        '16 battute a 76 bpm',
        { ritmo: 'r-bassoaccordo', accordo: 'C', bpm: 76, battute: 16 }),
      P('l5-down-valley', 'giro',
        'Down in the Valley',
        'Due soli accordi tenuti a lungo, in tre quarti: perfetta per il basso e accordo senza doversi preoccupare dei cambi.',
        'Suonarla dall\'inizio alla fine',
        { brano: 'down-in-the-valley', bpm: 80 }),
      P('l5-sospesi', 'accordo',
        'Re sospeso quarta',
        'Il Re con il mignolo aggiunto sul cantino. Non è un accordo nuovo da imparare: è il Re che si muove. Alzare e togliere quel dito sopra un Re tenuto è metà del folk degli ultimi cinquant\'anni.',
        'Suonarlo pulito 8 volte di fila',
        { accordo: 'Dsus4', ripetizioni: 8 }),
      P('l5-giro-sospesi', 'giro',
        'Il Re che respira',
        'Un accordo solo, con il mignolo che sale e scende. Suonalo in arpeggio e senti come la musica va avanti senza che tu cambi niente.',
        'Il giro intero senza fermarti',
        { brano: 'giro-sospesi', bpm: 64, tollera: ['Dsus2'] }),
      P('l5-cadd9', 'accordo',
        'Do con nona aggiunta',
        'Il Do con il mignolo sulla 2ª corda al 3° tasto. Serve a una cosa molto pratica: anulare e mignolo restano INCOLLATI lì mentre passi da Sol a Re a Mi minore a questo. Si muovono due dita invece di sei.',
        'Suonarlo pulito 8 volte di fila',
        { accordo: 'Cadd9', ripetizioni: 8 }),
      P('l5-quattro-cadd9', 'giro',
        'Il giro dei quattro accordi, versione pigra',
        'Lo stesso giro del livello 3 tenendo le due dita ferme sul 3° tasto per tutti e quattro gli accordi. Non è una scorciatoia: lo fanno tutti, ed è il motivo per cui certi accompagnamenti suonano fluidi.',
        'Il giro intero senza fermarti',
        { brano: 'giro-quattro-cadd9', bpm: 78 }),
      P('l5-scarborough', 'giro',
        'Scarborough Fair',
        'Valzer in minore, molto lento: si sente ogni cambio sporco. È anche il brano da fingerpicking per eccellenza.',
        'Suonarla dall\'inizio alla fine in arpeggio',
        { brano: 'scarborough', bpm: 74 }),
      P('l5-amazing', 'giro',
        'Amazing Grace',
        'In tre quarti. Il valzer costringe a contare: UN-due-tre. Il Sol settima in mezzo tira verso il Do, e adesso lo senti.',
        'Suonarla dall\'inizio alla fine',
        { brano: 'amazing-grace', bpm: 80 }),
    ],
  },

  {
    id: 'l6',
    nome: 'Livello 6 — Il barré',
    sottotitolo: 'Il muro. Ha un livello suo perché è qui che si smette',
    passi: [
      P('l6-cosa-e', 'lettura',
        'Perché il barré ronza (e non è la forza)',
        '',
        'Risposta esatta alla domanda',
        {
          punti: [
            'Il barré è un dito solo — l\'indice — che fa da capotasto su più corde insieme. Da lì in su ci metti sopra una forma che già conosci.',
            'Ronza a tutti, per settimane. Non sei tu. Serve a saperlo prima, perché il motivo per cui la gente molla la chitarra al secondo mese è credere di non essere portata.',
            'La forza NON è la risposta. Un indice steso di piatto ha delle valli fra le falangi, e le corde finiscono lì dentro: puoi spingere quanto vuoi, quelle non suonano. Ruota l\'indice di un quarto di giro sul FIANCO esterno, quello verso il pollice: è duro, liscio e senza avvallamenti.',
            'Il pollice va DIETRO il manico, più o meno di fronte all\'indice, e spinge in avanti. Il barré non si fa schiacciando: si fa stringendo una pinza fra pollice e indice.',
            'Tira il gomito destro... no: avvicina il gomito SINISTRO al corpo e lascia scendere la spalla. Se il gomito sta lontano dal fianco, il polso non può ruotare e il barré non viene, punto.',
            'Metti il barré il più vicino possibile alla barretta, come per ogni altra nota. Un millimetro più indietro e devi raddoppiare la forza.',
            'Non serve che TUTTE le corde sotto il barré suonino: in molte forme quelle di mezzo sono premute da altre dita. Concentra la pressione dove serve davvero — di solito la 1ª, la 2ª e la 6ª.',
            'Due minuti al giorno per due settimane battono un\'ora una volta sola. È forza di resistenza in un dito che non l\'ha mai usata così: cresce col tempo, non con l\'insistenza.',
          ],
          quiz: [{
            d: 'Il barré ronza sulle corde di mezzo. Qual è la prima cosa da provare?',
            opzioni: ['Premere molto più forte', 'Ruotare l\'indice sul fianco esterno e avvicinarlo alla barretta', 'Cambiare corde'],
            giusta: 1,
            perche: 'Di piatto, l\'indice ha delle valli fra le falangi e le corde ci cadono dentro: nessuna forza le fa suonare. Sul fianco esterno il dito è duro e liscio, e serve MENO pressione, non di più.',
          }],
        }),
      P('l6-rem7', 'accordo',
        'Re minore settima (mezzo barré)',
        'L\'indice steso su DUE corde soltanto, le due acute al 1° tasto. È il barré in miniatura, ed è l\'allenamento onesto per quello grande: stesso movimento, un decimo della fatica.',
        'Suonarlo pulito 8 volte di fila',
        { accordo: 'Dm7', ripetizioni: 8 }),
      P('l6-fa-facile', 'accordo',
        'Fa maggiore, versione a quattro corde',
        'Mezzo barré sulle due corde acute più medio e anulare. Suona un Fa vero, gli manca solo il basso. Serve a non fermare la canzone mentre il barré grande matura — e nessuno ti chiederà mai indietro le due corde che mancano.',
        'Suonarlo pulito 8 volte di fila',
        { accordo: 'F-facile', ripetizioni: 8 }),
      P('l6-cambio-cf', 'cambio',
        'Cambio Do ↔ Fa (versione facile)',
        'Il cambio che apre metà repertorio in Do. Lentissimo: il mezzo barré va appoggiato tutto insieme, non un pezzo alla volta.',
        '16 battute a 60 bpm',
        { accordi: ['C', 'F-facile'], bpm: 60, battute: 16 }),
      P('l6-fadiesism', 'accordo',
        'Fa# minore — il primo barré vero',
        'E si comincia da questo, non dal Fa. È il Mi minore col barré: sopra all\'indice ci sono solo DUE dita, e sono quelle di un accordo che suoni dal primo giorno. Al 2° tasto le corde sono anche meno tese che al 1°. È il barré più facile che esista, ed è un errore incontrarlo dopo il Fa.',
        'Suonarlo pulito 8 volte di fila',
        { accordo: 'F#m', ripetizioni: 8 }),
      P('l6-resistenza', 'ritmo',
        'Due minuti di resistenza sul barré',
        'Una pennata per battito, lenta, tenendo il Fa# minore. Non è un esercizio di ritmo: è un esercizio di RESISTENZA per l\'indice. Se comincia a bruciare, fermati — domani ne farai due minuti di più.',
        '16 battute a 60 bpm',
        { ritmo: 'r-giu4', accordo: 'F#m', bpm: 60, battute: 16 }),
      P('l6-fa', 'accordo',
        'Fa maggiore — il barré completo',
        'La forma del Mi maggiore col capotasto finto: l\'indice su tutte e sei le corde al 1° tasto. È il punto più duro del primo anno, e la ragione è banale — al 1° tasto le corde sono più tese che in qualunque altro punto del manico. Se al 5° tasto ti riesce e qui no, non stai sbagliando niente: stai solo combattendo con più tensione.',
        'Suonarlo pulito 8 volte di fila',
        { accordo: 'F', ripetizioni: 8 }),
      P('l6-ascolta-fa', 'ascolta',
        'Il microfono controlla il Fa',
        'Il giudice onesto. A orecchio un barré mezzo ronzante sembra "quasi giusto": qui vedi ESATTAMENTE quale corda non sta uscendo, e di solito è sempre la stessa. Sapere quale cambia tutto l\'allenamento.',
        '4 accordi riconosciuti come corretti',
        { accordo: 'F', corretti: 4 }),
      P('l6-mobile', 'lettura',
        'La forma mobile: impararne una vuol dire impararle tutte',
        '',
        'Risposta esatta alla domanda',
        {
          punti: [
            'Il barré è un capotasto fatto col dito. Sposti tutta la forma di un tasto e l\'accordo sale di un semitono, senza cambiare una dita.',
            'La forma del Mi maggiore col barré: al 1° tasto è Fa, al 2° Fa♯, al 3° Sol, al 5° La, al 7° Si. La nota che dà il nome è quella che l\'indice preme sulla 6ª corda.',
            'La forma del La maggiore col barré: al 1° tasto è Sib, al 3° Do, al 5° Re. Qui il nome lo dà la 5ª corda.',
            'Stessa cosa per i minori: forma di Mi minore (Fa♯m al 2°, Solm al 3°) e forma di La minore (Sim al 2°, Dom al 3°).',
            'Vuol dire che con quattro forme hai TUTTI i maggiori e TUTTI i minori del manico. È il momento in cui la chitarra smette di essere un elenco di posizioni da memorizzare.',
            'Più sali sul manico, meno le corde sono tese e meno forza serve. Prova il tuo barré al 5° tasto prima di riprovarlo al 1°: la differenza ti dirà che il problema non era il dito.',
          ],
          quiz: [{
            d: 'Suoni la forma del Fa (barré su tutte e sei) spostata al 3° tasto. Che accordo è?',
            opzioni: ['Fa♯', 'Sol', 'La'],
            giusta: 1,
            perche: 'La nota della 6ª corda al 3° tasto è un Sol, e in questa forma è lei a dare il nome. Dal 1° tasto (Fa) al 3° ci sono due semitoni: Fa → Fa♯ → Sol.',
          }],
        }),
      P('l6-sol-barre', 'accordo',
        'Sol col barré (la stessa forma, due tasti più su)',
        'La prova che il passo precedente non era teoria: identico al Fa, spostato al 3° tasto. Le corde sono meno tese e ti accorgerai che è più facile — dello stesso accordo che credevi impossibile.',
        'Suonarlo pulito 8 volte di fila',
        { accordo: 'G-barre', ripetizioni: 8 }),
      P('l6-sim', 'accordo',
        'Si minore',
        'La forma del La minore col barré al 2° tasto. Serve in mezzo pop italiano, e finora l\'hai sempre evitato: da qui in poi non serve più.',
        'Suonarlo pulito 8 volte di fila',
        { accordo: 'Bm', ripetizioni: 8 }),
      P('l6-cambio-gsim', 'cambio',
        'Cambio Sol ↔ Si minore',
        'Da un accordo a corde aperte a un barré e ritorno, a tempo. È il cambio che separa "so fare il barré fermo" da "so usare il barré".',
        '16 battute a 60 bpm',
        { accordi: ['G', 'Bm'], bpm: 60, battute: 16 }),
      P('l6-canone', 'giro',
        'Il giro del Canone',
        'Pachelbel, 1680 circa, e da allora non ha mai smesso. Otto battute che si richiudono da sole, con un Si minore in mezzo: è il giro che ti costringe a usare il barré dentro la musica invece che da fermo.',
        'Il giro intero senza fermarti',
        { brano: 'giro-canone', bpm: 68 }),
      P('l6-rising-sun', 'giro',
        'House of the Rising Sun',
        'Sei ottavi, in arpeggio, e un Fa in mezzo. Finché il barré non regge suonalo con il Fa a quattro corde: la canzone funziona lo stesso, e intanto il dito cresce.',
        'Suonarla dall\'inizio alla fine',
        { brano: 'rising-sun', bpm: 68 }),
    ],
  },

  {
    id: 'l7',
    nome: 'Livello 7 — Travis picking',
    sottotitolo: 'Il pollice che cammina da solo mentre le dita fanno altro',
    passi: [
      P('l7-cosa-e', 'lettura',
        'Come si impara il Travis (e come NON si impara)',
        '',
        'Risposta esatta alla domanda',
        {
          punti: [
            'Travis picking: il pollice alterna i bassi a tempo costante, e le altre dita entrano NEGLI SPAZI in mezzo. Le due mani destre fanno due cose diverse nello stesso momento, ed è per questo che sembra magia.',
            'Il modo sbagliato di impararlo, quello che fanno tutti: suonare lo schema intero a velocità ridotta. Non funziona, perché a velocità ridotta puoi ancora PENSARE a ogni dito — e il Travis funziona solo quando il pollice non lo pensi più.',
            'Il modo che funziona: il pollice da solo, finché non cammina mentre parli con qualcuno. Poi UN dito in mezzo, e solo quello, per giorni. Poi il secondo.',
            'Il pollice non deve rallentare quando entra un dito. Se rallenta, hai aggiunto il dito troppo presto: torna indietro di un passo.',
            'Aiuta smorzare appena i bassi appoggiando il bordo del palmo destro sul ponte: i bassi diventano corti e asciutti, e si sente meglio la differenza con le dita.',
            'È il suono di mezza musica americana — e una volta che il pollice cammina non si dimentica più, come andare in bicicletta.',
          ],
          quiz: [{
            d: 'Il pollice alterna bene, ma appena aggiungi l\'indice rallenta. Che fai?',
            opzioni: ['Rallenti tutto e continui', 'Torni al pollice da solo per qualche giorno', 'Aggiungi anche il medio, tanto ormai'],
            giusta: 1,
            perche: 'Il pollice che rallenta è il segnale che sta ancora occupando la tua attenzione. Fino a quando non è automatico, ogni dito aggiunto lo rimette in discussione: si torna indietro di un passo, non si spinge avanti.',
          }],
        }),
      P('l7-pollice', 'ritmo',
        'Il pollice alternato, ancora',
        'Sì, di nuovo. Ma adesso a occhi chiusi e per trentadue battute. Se ci riesci mentre pensi a cosa mangi stasera, sei pronto per il resto.',
        '32 battute a 72 bpm',
        { ritmo: 'a-basso-alternato', accordo: 'C', bpm: 72, battute: 32 }),
      P('l7-travis-1', 'ritmo',
        'Travis, primo passo: pollice più un dito',
        'Il pollice alternato più il MEDIO, e nient\'altro, in mezzo alla seconda e alla quarta pulsazione. Resta qui finché non è noioso.',
        '32 battute a 66 bpm',
        { ritmo: 'a-travis-semplice', accordo: 'C', bpm: 66, battute: 32 }),
      P('l7-travis-2', 'ritmo',
        'Travis completo',
        'Adesso entrano anche indice e anulare. Se il pollice tentenna, torna al passo precedente: non è una sconfitta, è il metodo.',
        '32 battute a 66 bpm',
        { ritmo: 'a-travis', accordo: 'C', bpm: 66, battute: 32 }),
      P('l7-travis-g', 'ritmo',
        'Travis sul Sol',
        'Cambia l\'accordo e cambiano le due corde del pollice. Le altre dita restano dove sono: è la stessa lezione del livello 5, con più cose che girano.',
        '32 battute a 66 bpm',
        { ritmo: 'a-travis', accordo: 'G', bpm: 66, battute: 32 }),
      P('l7-wildwood', 'giro',
        'Wildwood Flower',
        'Del 1860, resa celebre dalla Carter Family: è IL pezzo del basso alternato. Suonalo lento e lascia che sia il pollice a tenere il tempo, non il piede.',
        'Suonarla dall\'inizio alla fine',
        { brano: 'wildwood-flower', bpm: 76 }),
      P('l7-sloop', 'giro',
        'Sloop John B',
        'Sedici battute e tre accordi: abbastanza lunga da farti perdere il filo, abbastanza semplice da non darti scuse.',
        'Suonarla dall\'inizio alla fine',
        { brano: 'sloop-john-b', bpm: 88 }),
      P('l7-molly', 'giro',
        'Molly Malone',
        'Valzer in arpeggio con quattro accordi che scendono. Prova l\'arpeggio da valzer invece del Travis: è lo stesso principio in tre quarti.',
        'Suonarla dall\'inizio alla fine',
        { brano: 'molly-malone', bpm: 86 }),
    ],
  },

  {
    id: 'l8',
    nome: 'Livello 8 — Il colore',
    sottotitolo: 'Settime, sospese, none: gli accordi che fanno sembrare che tu sappia suonare',
    passi: [
      P('l8-accorda', 'accordatura',
        'Accorda con cura',
        'Da qui in poi si usano accordi con quattro note diverse: una corda calante non stona più "un po\'", stona e basta.',
        'Tutte e sei le corde entro 5 centesimi',
        {}),
      P('l8-cmaj7', 'accordo',
        'Do maggiore settima',
        'Il Do a cui TOGLI l\'indice. Un dito in meno e suona come un pomeriggio di settembre: è il miglior rapporto fra fatica e resa di tutta la chitarra.',
        'Suonarlo pulito 8 volte di fila',
        { accordo: 'Cmaj7', ripetizioni: 8 }),
      P('l8-em7', 'accordo',
        'Mi minore settima',
        'Un dito solo, e suonano tutte e sei le corde. Mettilo al posto di un Mi minore in un giro lento e senti la differenza.',
        'Suonarlo pulito 8 volte di fila',
        { accordo: 'Em7', ripetizioni: 8 }),
      P('l8-am7', 'accordo',
        'La minore settima',
        'Il La minore a cui togli il dito di mezzo. Due dita.',
        'Suonarlo pulito 8 volte di fila',
        { accordo: 'Am7', ripetizioni: 8 }),
      P('l8-fmaj7', 'accordo',
        'Fa maggiore settima',
        'Il Fa senza barré e senza fatica: quattro corde, tre dita. Nei giri lenti sta al posto del Fa e nessuno protesta.',
        'Suonarlo pulito 8 volte di fila',
        { accordo: 'Fmaj7', ripetizioni: 8 }),
      P('l8-gmaj7', 'accordo',
        'Sol maggiore settima',
        'Il Sol con il cantino al 2° tasto invece che al 3°. Serve per chiudere il giro del jazz.',
        'Suonarlo pulito 8 volte di fila',
        { accordo: 'Gmaj7', ripetizioni: 8 }),
      P('l8-ii-v-i', 'giro',
        'ii–V–I, il giro del jazz',
        'La minore settima, Re settima, Sol maggiore settima. Tre accordi che si passano la palla e chiudono: su questo è costruito quasi tutto lo standard jazz, e adesso li hai tutti e tre.',
        'Il giro intero senza fermarti',
        { brano: 'giro-ii-v-i', bpm: 72 }),
      P('l8-sospese', 'accordo',
        'La sospeso quarta',
        'Né allegro né triste: manca la terza, che è la nota che decide. Da solo sta in sospeso, e per questo chiede di risolvere sul La.',
        'Suonarlo pulito 8 volte di fila',
        { accordo: 'Asus4', ripetizioni: 8 }),
      P('l8-blues-la', 'giro',
        'Blues di 12 battute in La',
        'La stessa forma del livello 4 spostata di tonalità: la prova che nel blues contano i numeri, non i nomi.',
        'Dodici battute senza perdere il conto',
        { brano: 'blues-la', bpm: 84 }),
      P('l8-reggae', 'ritmo',
        'Il reggae: suonare solo i controtempi',
        'Sui battiti pieni non suoni niente. Conta a voce "1 e 2 e 3 e 4 e" e suona solo sulle "e". È l\'esercizio più difficile di tutto il percorso e non c\'entra con le dita.',
        '16 battute a 72 bpm',
        { ritmo: 'r-reggae', accordo: 'Am7', bpm: 72, battute: 16 }),
      P('l8-orecchio', 'orecchio',
        'Riconosci il colore',
        'Maggiore, minore, settima, maggiore settima. A questo punto la differenza la senti: si tratta solo di darle un nome.',
        '8 risposte esatte',
        { modo: 'quale', opzioni: ['G', 'Em', 'C', 'Am7', 'D7', 'Cmaj7'], scelte: 3, corrette: 8 }),
      P('l8-basso-scendente', 'lettura',
        'Il basso che cammina, e la barra nei nomi',
        '',
        'Risposta esatta alla domanda',
        {
          punti: [
            'Un nome con la barra — Re/Fa♯, Sol/Si — dice due cose: l\'accordo prima della barra, e quale nota va SOTTO dopo la barra.',
            'Non sono accordi nuovi da imparare. Sono quelli che sai gia, suonati facendo partire la pennata da un\'altra corda, o aggiungendo un dito sulla 6ª.',
            'Servono a una cosa sola e si sente subito: far scendere il basso un gradino alla volta mentre sopra gli accordi cambiano. Sol, poi Re con il Fa♯ sotto, poi Mi minore: il basso fa Sol, Fa♯, Mi. Senza quel Fa♯ salterebbe di tre gradini.',
            'Il Do con il Mi al basso e il piu economico di tutti: e il Do di sempre, e basta NON smorzare la 6ª corda.',
            'Il Sol con il Si al basso sta fra il Sol e il La minore: due dita, e il giro smette di saltare.',
            'Se il basso non e la nota giusta, l\'accordo suona lo stesso ma il movimento sparisce: quello che si sente non e l\'accordo, e la linea che fa la corda piu grave.',
          ],
          quiz: [{
            d: 'Che differenza c\'e fra un Re e un Re/Fa♯?',
            opzioni: [
              'Nessuna: il Fa♯ e gia dentro il Re maggiore',
              'Le note sono le stesse, ma nel secondo il Fa♯ sta al BASSO, sotto tutte le altre',
              'Il secondo ha una nota in piu che il primo non ha',
            ],
            giusta: 1,
            perche: 'Il Re maggiore contiene gia il Fa♯: la differenza non e quali note ci sono, e quale sta sotto. Ed e proprio quella che si sente, perche il basso e la voce che l\'orecchio segue.',
          }],
        }),
      P('l8-do-mi', 'accordo',
        'Do con il Mi al basso',
        'La stessa mano del Do. L\'unica differenza e che la 6ª corda, invece di smorzarla, la suoni. Prova ad alternare i due: cambia solo la corda da cui parti, e si sente.',
        'Suonarlo pulito 8 volte di fila',
        { accordo: 'C/E', ripetizioni: 8 }),
      P('l8-sol-si', 'accordo',
        'Sol con il Si al basso',
        'Due dita: indice sulla 5ª al 2° tasto, anulare sulla 1ª al 3°. La 6ª non si suona. E il gradino fra il Sol e il La minore.',
        'Suonarlo pulito 8 volte di fila',
        { accordo: 'G/B', ripetizioni: 8 }),
      P('l8-re-fadiesis', 'accordo',
        'Re con il Fa# al basso',
        'Il Re di sempre piu un dito sulla 6ª al 2° tasto — mignolo, oppure il pollice che sporge sopra il manico, come fanno in tanti. E il gradino fra il Sol e il Mi minore.',
        'Suonarlo pulito 8 volte di fila',
        { accordo: 'D/F#', ripetizioni: 8 }),
      P('l8-giro-basso', 'giro',
        'Il basso che scende',
        'Otto battute in cui la corda piu grave scende un gradino alla volta: Sol, Fa♯, Mi, Re, Do, Si, La. Suonalo lento e ascolta SOLO il basso — gli accordi sopra li conosci gia tutti.',
        'Il giro intero senza fermarti',
        { brano: 'giro-basso-scendente', bpm: 64 }),
      P('l8-cambio-libero', 'cambio',
        'Cambio a sorteggio, fra tutto quello che sai',
        'Il programma pesca due accordi a caso fra quelli che hai segnato come fatti, e accelera da solo. È l\'unico esercizio che non puoi preparare, ed è quello che dice davvero a che punto sei.',
        '32 battute con la velocità che sale',
        { accordi: 'appresi', bpm: 76, battute: 32, salita: 2 }),
      P('l8-ode', 'giro',
        'Inno alla gioia',
        'Melodia che riconoscono tutti su un accompagnamento elementare. Suonala per qualcuno: è per questo che hai fatto tutto il resto.',
        'Suonarla dall\'inizio alla fine',
        { brano: 'ode-gioia', bpm: 92 }),
    ],
  },
];

export const PASSI = LIVELLI.flatMap((l) => l.passi.map((p) => ({ ...p, livello: l.id })));
export const PER_ID = new Map(PASSI.map((p) => [p.id, p]));

export function passo(id) {
  return PER_ID.get(id) || null;
}

/** Accordi introdotti dal percorso fino a un certo passo (compreso). */
export function accordiFinoA(idPasso) {
  const fine = PASSI.findIndex((p) => p.id === idPasso);
  const entro = fine < 0 ? PASSI : PASSI.slice(0, fine + 1);
  const visti = [];
  entro.forEach((p) => {
    if (p.tipo === 'accordo' && !visti.includes(p.dati.accordo)) visti.push(p.dati.accordo);
  });
  return visti;
}

/** Accordi che l'utente ha già segnato come fatti: alimenta i "cambi a sorteggio". */
export function accordiAppresi(passiFatti) {
  const visti = PASSI
    .filter((p) => p.tipo === 'accordo' && passiFatti[p.id])
    .map((p) => p.dati.accordo);
  return visti.length >= 2 ? visti : ['Em', 'Am', 'G'];
}

/** Il prossimo passo non fatto: è la risposta a "che faccio oggi?". */
export function prossimoPasso(passiFatti) {
  return PASSI.find((p) => !passiFatti[p.id]) || null;
}

export function avanzamentoLivello(livello, passiFatti) {
  const fatti = livello.passi.filter((p) => passiFatti[p.id]).length;
  return { fatti, totale: livello.passi.length, quota: fatti / livello.passi.length };
}
